<?php

namespace App\Repository;

use App\Entity\Contact;
use App\Service\ContactService;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;
use Doctrine\ORM\EntityManagerInterface;


/**
 * ServiceEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends ServiceEntityRepository
{
    

    
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Contact::class);
       
    }

    /**
     * @return messages[]
     */
  public function findAllOrderedByName(): array
  
    {
        
        $em = $this->getEntityManager();
        $queryBuilder = $em->createQueryBuilder();
        $queryBuilder->select('m')
                     ->from('App\Entity\Contact', 'm')
                    ->orderBy('m.name', 'ASC');

        $query = $queryBuilder->getQuery();
        $messages = $query->getResult();

        return $messages;
    }
    
}
